<?php

namespace ClubBundle\Repository;

/**
 * AraEvenementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AraEvenementsRepository extends \Doctrine\ORM\EntityRepository
{
}
