<?php

namespace ClubBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AraRepository extends EntityRepository
{
}
