<?php

namespace ClubBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * av1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class av1Repository extends EntityRepository
{
}
