<?php

namespace ClubBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * av2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class av2Repository extends EntityRepository
{
}
