<?php

namespace ClubBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * club_supRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class club_supRepository extends EntityRepository
{
}
