<?php

namespace ClubBundle\Repository;

/**
 * EvAraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvAraRepository extends \Doctrine\ORM\EntityRepository
{
}
