<?php

namespace ClubBundle\Repository;

/**
 * EvRcvlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvRcvlRepository extends \Doctrine\ORM\EntityRepository
{
}
