<?php

namespace ClubBundle\Repository;

/**
 * EvSupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvSupRepository extends \Doctrine\ORM\EntityRepository
{
}
