<?php

namespace ClubBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MembresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembresRepository extends EntityRepository
{
}
