<?php

namespace ClubBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageMembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageMembreRepository extends EntityRepository
{
}
