<?php

namespace ClubBundle\Repository;

/**
 * SupEvenementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupEvenementsRepository extends \Doctrine\ORM\EntityRepository
{
}
