<?php

namespace Proxies\__CG__\ClubBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class presentation extends \ClubBundle\Entity\presentation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'image', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'iname', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'image2', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'iname2', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'id', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'title', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'soustitre1', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'paragraph1', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'soustitre2', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'paragraph2'];
        }

        return ['__isInitialized__', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'image', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'iname', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'image2', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'iname2', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'id', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'title', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'soustitre1', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'paragraph1', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'soustitre2', '' . "\0" . 'ClubBundle\\Entity\\presentation' . "\0" . 'paragraph2'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (presentation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setIname($iname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIname', [$iname]);

        return parent::setIname($iname);
    }

    /**
     * {@inheritDoc}
     */
    public function getIname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIname', []);

        return parent::getIname();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage2($image2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage2', [$image2]);

        return parent::setImage2($image2);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage2', []);

        return parent::getImage2();
    }

    /**
     * {@inheritDoc}
     */
    public function setIname2($iname2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIname2', [$iname2]);

        return parent::setIname2($iname2);
    }

    /**
     * {@inheritDoc}
     */
    public function getIname2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIname2', []);

        return parent::getIname2();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoustitre1($soustitre1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoustitre1', [$soustitre1]);

        return parent::setSoustitre1($soustitre1);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoustitre1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoustitre1', []);

        return parent::getSoustitre1();
    }

    /**
     * {@inheritDoc}
     */
    public function setParagraph1($paragraph1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParagraph1', [$paragraph1]);

        return parent::setParagraph1($paragraph1);
    }

    /**
     * {@inheritDoc}
     */
    public function getParagraph1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParagraph1', []);

        return parent::getParagraph1();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoustitre2($soustitre2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoustitre2', [$soustitre2]);

        return parent::setSoustitre2($soustitre2);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoustitre2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoustitre2', []);

        return parent::getSoustitre2();
    }

    /**
     * {@inheritDoc}
     */
    public function setParagraph2($paragraph2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParagraph2', [$paragraph2]);

        return parent::setParagraph2($paragraph2);
    }

    /**
     * {@inheritDoc}
     */
    public function getParagraph2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParagraph2', []);

        return parent::getParagraph2();
    }

}
