<?php

namespace Proxies\__CG__\ClubBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AraEvenements extends \ClubBundle\Entity\AraEvenements implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = ['iname' => NULL, 'iname2' => NULL, 'iname3' => NULL, 'iname4' => NULL, 'iname5' => NULL, 'iname6' => NULL, 'iname7' => NULL, 'iname8' => NULL, 'iname9' => NULL, 'iname10' => NULL, 'iname11' => NULL, 'iname12' => NULL, 'iname13' => NULL, 'iname14' => NULL, 'iname15' => NULL, 'iname16' => NULL, 'iname17' => NULL, 'iname18' => NULL, 'iname19' => NULL, 'iname20' => NULL, 'iname21' => NULL, 'iname22' => NULL, 'iname23' => NULL, 'iname24' => NULL, 'iname25' => NULL, 'iname26' => NULL, 'iname27' => NULL, 'iname28' => NULL, 'iname29' => NULL, 'iname30' => NULL];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->iname, $this->iname2, $this->iname3, $this->iname4, $this->iname5, $this->iname6, $this->iname7, $this->iname8, $this->iname9, $this->iname10, $this->iname11, $this->iname12, $this->iname13, $this->iname14, $this->iname15, $this->iname16, $this->iname17, $this->iname18, $this->iname19, $this->iname20, $this->iname21, $this->iname22, $this->iname23, $this->iname24, $this->iname25, $this->iname26, $this->iname27, $this->iname28, $this->iname29, $this->iname30);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'image', 'iname', 'image2', 'iname2', 'image3', 'iname3', 'image4', 'iname4', 'image5', 'iname5', 'image6', 'iname6', 'image7', 'iname7', 'image8', 'iname8', 'image9', 'iname9', 'image10', 'iname10', 'image11', 'iname11', 'image12', 'iname12', 'image13', 'iname13', 'image14', 'iname14', 'image15', 'iname15', 'image16', 'iname16', 'image17', 'iname17', 'image18', 'iname18', 'image19', 'iname19', 'image20', 'iname20', 'image21', 'iname21', 'image22', 'iname22', 'image23', 'iname23', 'image24', 'iname24', 'image25', 'iname25', 'image26', 'iname26', 'image27', 'iname27', 'image28', 'iname28', 'image29', 'iname29', 'image30', 'iname30', '' . "\0" . 'ClubBundle\\Entity\\AraEvenements' . "\0" . 'id', '' . "\0" . 'ClubBundle\\Entity\\AraEvenements' . "\0" . 'title', '' . "\0" . 'ClubBundle\\Entity\\AraEvenements' . "\0" . 'paragraph'];
        }

        return ['__isInitialized__', 'image', 'image2', 'image3', 'image4', 'image5', 'image6', 'image7', 'image8', 'image9', 'image10', 'image11', 'image12', 'image13', 'image14', 'image15', 'image16', 'image17', 'image18', 'image19', 'image20', 'image21', 'image22', 'image23', 'image24', 'image25', 'image26', 'image27', 'image28', 'image29', 'image30', '' . "\0" . 'ClubBundle\\Entity\\AraEvenements' . "\0" . 'id', '' . "\0" . 'ClubBundle\\Entity\\AraEvenements' . "\0" . 'title', '' . "\0" . 'ClubBundle\\Entity\\AraEvenements' . "\0" . 'paragraph'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AraEvenements $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->iname, $this->iname2, $this->iname3, $this->iname4, $this->iname5, $this->iname6, $this->iname7, $this->iname8, $this->iname9, $this->iname10, $this->iname11, $this->iname12, $this->iname13, $this->iname14, $this->iname15, $this->iname16, $this->iname17, $this->iname18, $this->iname19, $this->iname20, $this->iname21, $this->iname22, $this->iname23, $this->iname24, $this->iname25, $this->iname26, $this->iname27, $this->iname28, $this->iname29, $this->iname30);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIname($iname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIname', [$iname]);

        return parent::setIname($iname);
    }

    /**
     * {@inheritDoc}
     */
    public function getIname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIname', []);

        return parent::getIname();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setIname2($iname2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIname2', [$iname2]);

        return parent::setIname2($iname2);
    }

    /**
     * {@inheritDoc}
     */
    public function getIname2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIname2', []);

        return parent::getIname2();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage2($image2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage2', [$image2]);

        return parent::setImage2($image2);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage2', []);

        return parent::getImage2();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname3($iname3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname3', [$iname3]);

        return parent::setiname3($iname3);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname3', []);

        return parent::getiname3();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage3($image3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage3', [$image3]);

        return parent::setimage3($image3);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage3', []);

        return parent::getimage3();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname4($iname4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname4', [$iname4]);

        return parent::setiname4($iname4);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname4', []);

        return parent::getiname4();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage4($image4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage4', [$image4]);

        return parent::setimage4($image4);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage4', []);

        return parent::getimage4();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage5($image5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage5', [$image5]);

        return parent::setimage5($image5);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage5', []);

        return parent::getimage5();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname5($iname5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname5', [$iname5]);

        return parent::setiname5($iname5);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname5', []);

        return parent::getiname5();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage6($image6)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage6', [$image6]);

        return parent::setimage6($image6);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage6()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage6', []);

        return parent::getimage6();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname6($iname6)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname6', [$iname6]);

        return parent::setiname6($iname6);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname6()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname6', []);

        return parent::getiname6();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage7($image7)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage7', [$image7]);

        return parent::setimage7($image7);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage7()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage7', []);

        return parent::getimage7();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname7($iname7)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname7', [$iname7]);

        return parent::setiname7($iname7);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname7()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname7', []);

        return parent::getiname7();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage8($image8)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage8', [$image8]);

        return parent::setimage8($image8);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage8()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage8', []);

        return parent::getimage8();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname8($iname8)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname8', [$iname8]);

        return parent::setiname8($iname8);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname8()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname8', []);

        return parent::getiname8();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage9($image9)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage9', [$image9]);

        return parent::setimage9($image9);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage9()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage9', []);

        return parent::getimage9();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname9($iname9)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname9', [$iname9]);

        return parent::setiname9($iname9);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname9()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname9', []);

        return parent::getiname9();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage10($image10)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage10', [$image10]);

        return parent::setimage10($image10);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage10()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage10', []);

        return parent::getimage10();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname10($iname10)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname10', [$iname10]);

        return parent::setiname10($iname10);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname10()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname10', []);

        return parent::getiname10();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname11($iname11)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname11', [$iname11]);

        return parent::setiname11($iname11);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname11()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname11', []);

        return parent::getiname11();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage11($image11)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage11', [$image11]);

        return parent::setimage11($image11);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage11()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage11', []);

        return parent::getimage11();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname12($iname12)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname12', [$iname12]);

        return parent::setiname12($iname12);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname12()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname12', []);

        return parent::getiname12();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage12($image12)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage12', [$image12]);

        return parent::setimage12($image12);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage12()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage12', []);

        return parent::getimage12();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname13($iname13)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname13', [$iname13]);

        return parent::setiname13($iname13);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname13()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname13', []);

        return parent::getiname13();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage13($image13)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage13', [$image13]);

        return parent::setimage13($image13);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage13()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage13', []);

        return parent::getimage13();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname14($iname14)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname14', [$iname14]);

        return parent::setiname14($iname14);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname14()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname14', []);

        return parent::getiname14();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage14($image14)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage14', [$image14]);

        return parent::setimage14($image14);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage14()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage14', []);

        return parent::getimage14();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname15($iname15)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname15', [$iname15]);

        return parent::setiname15($iname15);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname15()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname15', []);

        return parent::getiname15();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage15($image15)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage15', [$image15]);

        return parent::setimage15($image15);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage15()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage15', []);

        return parent::getimage15();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname16($iname16)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname16', [$iname16]);

        return parent::setiname16($iname16);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname16()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname16', []);

        return parent::getiname16();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage16($image16)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage16', [$image16]);

        return parent::setimage16($image16);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage16()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage16', []);

        return parent::getimage16();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname17($iname17)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname17', [$iname17]);

        return parent::setiname17($iname17);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname17()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname17', []);

        return parent::getiname17();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage17($image17)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage17', [$image17]);

        return parent::setimage17($image17);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage17()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage17', []);

        return parent::getimage17();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname18($iname18)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname18', [$iname18]);

        return parent::setiname18($iname18);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname18()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname18', []);

        return parent::getiname18();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage18($image18)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage18', [$image18]);

        return parent::setimage18($image18);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage18()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage18', []);

        return parent::getimage18();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname19($iname19)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname19', [$iname19]);

        return parent::setiname19($iname19);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname19()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname19', []);

        return parent::getiname19();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage19($image19)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage19', [$image19]);

        return parent::setimage19($image19);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage19()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage19', []);

        return parent::getimage19();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname20($iname20)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname20', [$iname20]);

        return parent::setiname20($iname20);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname20()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname20', []);

        return parent::getiname20();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage20($image20)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage20', [$image20]);

        return parent::setimage20($image20);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage20()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage20', []);

        return parent::getimage20();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname21($iname21)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname21', [$iname21]);

        return parent::setiname21($iname21);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname21()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname21', []);

        return parent::getiname21();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage21($image21)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage21', [$image21]);

        return parent::setimage21($image21);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage21()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage21', []);

        return parent::getimage21();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname22($iname22)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname22', [$iname22]);

        return parent::setiname22($iname22);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname22()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname22', []);

        return parent::getiname22();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage22($image22)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage22', [$image22]);

        return parent::setimage22($image22);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage22()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage22', []);

        return parent::getimage22();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname23($iname23)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname23', [$iname23]);

        return parent::setiname23($iname23);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname23()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname23', []);

        return parent::getiname23();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage23($image23)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage23', [$image23]);

        return parent::setimage23($image23);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage23()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage23', []);

        return parent::getimage23();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname24($iname24)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname24', [$iname24]);

        return parent::setiname24($iname24);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname24()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname24', []);

        return parent::getiname24();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage24($image24)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage24', [$image24]);

        return parent::setimage24($image24);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage24()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage24', []);

        return parent::getimage24();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname25($iname25)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname25', [$iname25]);

        return parent::setiname25($iname25);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname25()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname25', []);

        return parent::getiname25();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage25($image25)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage25', [$image25]);

        return parent::setimage25($image25);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage25()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage25', []);

        return parent::getimage25();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname26($iname26)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname26', [$iname26]);

        return parent::setiname26($iname26);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname26()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname26', []);

        return parent::getiname26();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage26($image26)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage26', [$image26]);

        return parent::setimage26($image26);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage26()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage26', []);

        return parent::getimage26();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname27($iname27)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname27', [$iname27]);

        return parent::setiname27($iname27);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname27()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname27', []);

        return parent::getiname27();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage27($image27)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage27', [$image27]);

        return parent::setimage27($image27);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage27()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage27', []);

        return parent::getimage27();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname28($iname28)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname28', [$iname28]);

        return parent::setiname28($iname28);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname28()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname28', []);

        return parent::getiname28();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage28($image28)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage28', [$image28]);

        return parent::setimage28($image28);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage28()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage28', []);

        return parent::getimage28();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname29($iname29)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname29', [$iname29]);

        return parent::setiname29($iname29);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname29()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname29', []);

        return parent::getiname29();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage29($image29)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage29', [$image29]);

        return parent::setimage29($image29);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage29()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage29', []);

        return parent::getimage29();
    }

    /**
     * {@inheritDoc}
     */
    public function setiname30($iname30)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setiname30', [$iname30]);

        return parent::setiname30($iname30);
    }

    /**
     * {@inheritDoc}
     */
    public function getiname30()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getiname30', []);

        return parent::getiname30();
    }

    /**
     * {@inheritDoc}
     */
    public function setimage30($image30)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setimage30', [$image30]);

        return parent::setimage30($image30);
    }

    /**
     * {@inheritDoc}
     */
    public function getimage30()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimage30', []);

        return parent::getimage30();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setParagraph($paragraph)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParagraph', [$paragraph]);

        return parent::setParagraph($paragraph);
    }

    /**
     * {@inheritDoc}
     */
    public function getParagraph()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParagraph', []);

        return parent::getParagraph();
    }

}
