contact_index:
    path:     /
    defaults: { _controller: "ClubBundle:contact:index" }
    methods:  GET

contact_edit:
    path:     /{id}/edit
    defaults: { _controller: "ClubBundle:contact:edit" }
    methods:  [GET, POST]

contact_delete:
    path:     /{id}/delete
    defaults: { _controller: "ClubBundle:contact:delete" }
    methods:  DELETE
