evara_index:
    path:     /
    defaults: { _controller: "ClubBundle:EvAra:index" }
    methods:  GET

evara_edit:
    path:     /{id}/edit
    defaults: { _controller: "ClubBundle:EvAra:edit" }
    methods:  [GET, POST]

evara_delete:
    path:     /{id}/delete
    defaults: { _controller: "ClubBundle:EvAra:delete" }
    methods:  DELETE
