membres_index:
    path:     /
    defaults: { _controller: "ClubBundle:Membres:index" }
    methods:  GET

membres_edit:
    path:     /{id}/edit
    defaults: { _controller: "ClubBundle:Membres:edit" }
    methods:  [GET, POST]

membres_delete:
    path:     /{id}/delete
    defaults: { _controller: "ClubBundle:Membres:delete" }
    methods:  DELETE
