ClubBundle\Entity\club_sup:
    type: entity
    table: null
    repositoryClass: ClubBundle\Repository\club_supRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        soutitre:
            type: string
            length: 255
        paragraph:
            type: string
            length: 255
        iname:
            type: string
    lifecycleCallbacks: {  }
