ClubBundle\Entity\EvRcvl:
    type: entity
    table: null
    repositoryClass: ClubBundle\Repository\EvRcvlRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
    lifecycleCallbacks: {  }
