ClubBundle\Entity\PageMembre:
    type: entity
    table: null
    repositoryClass: ClubBundle\Repository\PageMembreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
    lifecycleCallbacks: {  }
