ClubBundle\Entity\Rcvl:
    type: entity
    table: null
    repositoryClass: ClubBundle\Repository\RcvlRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        soustitre:
            type: string
            length: 255
            column: Soustitre
        paragraph:
            type: string
            length: '600'
        iname:
            type: string
    lifecycleCallbacks: {  }
